# Generated by Django 5.0 on 2023-12-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishnpubschool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Comment',
            new_name='textcomment',
        ),
    ]
