# Generated by Django 5.0 on 2023-12-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishnpubschool', '0002_rename_comment_feedback_textcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='adform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('fathername', models.CharField(max_length=50)),
                ('mothername', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='admission',
        ),
    ]
