# Generated by Django 5.0 on 2023-12-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishnpubschool', '0003_adform_delete_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ragistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('psd', models.CharField(max_length=20)),
                ('psw_repeat', models.CharField(max_length=20)),
            ],
        ),
    ]
