# Generated by Django 5.0 on 2023-12-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishnpubschool', '0004_ragistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ragister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('psd', models.CharField(max_length=20)),
                ('psw_repeat', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ragistration',
        ),
    ]
