# Generated by Django 5.0 on 2023-12-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishnpubschool', '0005_ragister_delete_ragistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ragister',
            old_name='psd',
            new_name='password',
        ),
    ]
