# Generated by Django 5.0 on 2023-12-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishnpubschool', '0006_rename_psd_ragister_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ragister',
            old_name='psw_repeat',
            new_name='password_repeat',
        ),
    ]
