# Generated by Django 5.0 on 2023-12-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishnpubschool', '0007_rename_psw_repeat_ragister_password_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ragister',
            name='password_repeat',
        ),
    ]
