# Generated by Django 5.0 on 2023-12-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishnpubschool', '0008_remove_ragister_password_repeat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adform',
            old_name='type',
            new_name='types',
        ),
    ]
